### ISSUE TITLE
strip trailing '.', 'z', 'i' and 'p' charact'ers from the end of the download directory which breaks create_cbz

### ISSUE THREAD

**Issue by prahal** [izneo-get/izneo-get#53]
in izneo_get/tools.py "create_cbz":
`shutil.make_archive(zip_filepath.strip(".zip"), "zip", source_folder)`
does not only remove ".zip" but all trailing '.', 'z', 'i' and 'p' character from the end of the download irectory.

That is:
```
>>> path="DOWNLOADS/a..zip"
>>> path.strip(".zip")
'DOWNLOADS/a'
>>> path="DOWNLOADS/az.zip"
>>> path.strip(".zip")
'DOWNLOADS/a'
>>> path="DOWNLOADS/ai.zip"
>>> path.strip(".zip")
'DOWNLOADS/a'
>>> path="DOWNLOADS/ap.zip"
>>> path.strip(".zip")
'DOWNLOADS/a'
>>> path="DOWNLOADS/azip.zip"
>>> path.strip(".zip")
'DOWNLOADS/a'
>>> path="DOWNLOADS/apiz.zip"
>>> path.strip(".zip")
'DOWNLOADS/a'
```

I bet you intended to remove only the ".zip" extension, not any individual '.', 'z', 'I' and 'p' from the end of the directory name or any combination of these characters in any order from the end of this directory name.

This breaks downloading one of my album which name ends with 'i'

```
Destination : DOWNLOADS/<x>sari                                                                                                                       
Download pages: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 134/134 [02:37<00:00]
134 pages downloaded                           
Create CBZ...                                                                                                                                                                                 
Traceback (most recent call last):                                                                                                                                                            
  File "/home/prahal/Projects/WIP/Izneo/./izneo-get/izneo_get.py", line 5, in <module>                                                                                                        
    __main__.main()                                                                                                                                                                           
  File "/home/prahal/Projects/WIP/Izneo/izneo-get/izneo_get/__main__.py", line 105, in main                                                                                                   
    create_cbz(save_path)                                                                                                                                                                     
  File "/home/prahal/Projects/WIP/Izneo/izneo-get/izneo_get/tools.py", line 178, in create_cbz                                                                                                
    os.rename(zip_filepath, cbz_filepath)                                                                                                                                                     
FileNotFoundError: [Errno 2] No such file or directory: "DOWNLOADS/<x>sari.zip" -> "DOWNLOADS/<x>sari.cbz"
```

because the zip file created miss the ending 'i': `DOWNLOADS/<x>sar.zip

**Comment by prahal** [comment]
Without adding more dependencies os.path.splitext:
```
>>> path="ai.piz.zip"
>>> os.path.splitext(path)[0]
'ai.piz'
>>> path="ai.zip.zip"
>>> os.path.splitext(path)[0]
'ai.zip'
```
